---
os: linux
language: python
python: '3.8'

env:
  global:
  jobs:
    - MOLECULE_DISTRO: centos
      MOLECULE_DISTRO_TAG: 8
    - MOLECULE_DISTRO: centos
      MOLECULE_DISTRO_TAG: 7
    - MOLECULE_DISTRO: ubuntu
      MOLECULE_DISTRO_TAG: focal
    - MOLECULE_DISTRO: ubuntu
      MOLECULE_DISTRO_TAG: bionic
    - MOLECULE_DISTRO: ubuntu
      MOLECULE_DISTRO_TAG: xenial
    - MOLECULE_DISTRO: debian
      MOLECULE_DISTRO_TAG: 10
    - MOLECULE_DISTRO: debian
      MOLECULE_DISTRO_TAG: 9
    - MOLECULE_DISTRO: fedora
      MOLECULE_DISTRO_TAG: 33
    - MOLECULE_DISTRO: fedora
      MOLECULE_DISTRO_TAG: 32

dist: focal
services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
install:
  - pip install molecule-docker yamllint ansible-lint
before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
  - molecule test

branches:
  only:
    - master
    - /^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)([\.\-].*)?$/

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
